# Generated by Django 4.1.7 on 2023-03-29 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resaInterface.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=resaInterface.models.get_course_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=resaInterface.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('8h', '8h-9h'), ('9h', '9h-10h'), ('10h', '10h-11h'), ('11h', '11h-12h'), ('14h', '14h-15h'), ('15h', '15h-16h'), ('16h', '16h-17h'), ('17h', '17h-18h')], default='8h', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resaInterface.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resaInterface.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='resaInterface.school'),
        ),
    ]
